 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 plugins:
  - jekyll-seo-tag
 # theme: jekyll-theme-midnight
 remote_theme: Lunar-Dust/midnight
 gfm_quirks: paragraph_end
 baseurl: /Coding-Standards
 homeurl: https://frc2081.github.io/Coding-Standards
 repourl: https://github.com/frc2081/Coding-Standards
